/*
 * Rendon Estrada Jorge
 * 04/07/2023
 * Descripcion: Panel de Devoluciones que se muestra en el Dashboard 
 * Contiene la tabla de los prestamos y los botones con las acciones
 */

package vistas;

import java.awt.Color;

/**
 *
 * @author Jorge
 */
public class Devoluciones_Editar extends javax.swing.JPanel {

    /** Creates new form Usuarios */
    public Devoluciones_Editar() {
        initComponents();
        //Mando a llamar el metodo del LOOK & FEEL
        IniStyles();
        TextPrompt busq = new TextPrompt("TITULO DEL LIBRO", txt_Nombrelibro);
        TextPrompt busqId = new TextPrompt("ID DEL PRESTAMO", txt_IdPrestamo);
        
        //Agregar los botones al grupo
        group_btn.add(rb_Entregado);
        group_btn.add(rb_Pendiente);
    }
    
     private void IniStyles(){
        lbl_libro.putClientProperty("FlatLaf.styleClass", "large");
        lbl_libro.setForeground(Color.black);
        //Cambiar los text Field a redondeados
        txt_Nombrelibro.putClientProperty( "JComponent.roundRect", true );
        txt_IdPrestamo.putClientProperty( "JComponent.roundRect", true );
        //Cambiar los botones a redondeados
        btn_BuscarNombreLibro.putClientProperty( "JButton.buttonType", "roundRect" );
        btn_BuscarFolio.putClientProperty( "JButton.buttonType", "roundRect" );
        //Poner el combo box con elestilo
        cbx_Libro.putClientProperty( "JComponent.roundRect", true );
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_btn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_Nombrelibro = new javax.swing.JTextField();
        btn_BuscarNombreLibro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_Guardar = new javax.swing.JButton();
        txt_IdPrestamo = new javax.swing.JTextField();
        btn_BuscarFolio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Devoluciones_Editar = new javax.swing.JTable();
        cbx_Libro = new javax.swing.JComboBox<>();
        lbl_libro = new javax.swing.JLabel();
        rb_Entregado = new javax.swing.JRadioButton();
        rb_Pendiente = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_Nombrelibro.setBackground(new java.awt.Color(255, 255, 255));
        txt_Nombrelibro.setForeground(new java.awt.Color(0, 0, 0));
        txt_Nombrelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombrelibroActionPerformed(evt);
            }
        });

        btn_BuscarNombreLibro.setBackground(new java.awt.Color(0, 1, 248));
        btn_BuscarNombreLibro.setForeground(new java.awt.Color(255, 255, 255));
        btn_BuscarNombreLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        btn_BuscarNombreLibro.setText("Buscar");

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        btn_Guardar.setBackground(new java.awt.Color(0, 1, 248));
        btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btn_Guardar.setText("Guardar");

        txt_IdPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        txt_IdPrestamo.setForeground(new java.awt.Color(0, 0, 0));

        btn_BuscarFolio.setBackground(new java.awt.Color(0, 1, 248));
        btn_BuscarFolio.setForeground(new java.awt.Color(255, 255, 255));
        btn_BuscarFolio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        btn_BuscarFolio.setText("Buscar");

        tbl_Devoluciones_Editar.setBackground(new java.awt.Color(255, 255, 255));
        tbl_Devoluciones_Editar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "BUSCAR EN FOLIO..."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Devoluciones_Editar);

        lbl_libro.setText("LIBRO");

        rb_Entregado.setText("Entregado");

        rb_Pendiente.setText("Pendiente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_Pendiente)
                                    .addComponent(rb_Entregado)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Nombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_BuscarNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(txt_IdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lbl_libro))
                            .addComponent(btn_BuscarFolio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BuscarNombreLibro)
                    .addComponent(txt_Nombrelibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_BuscarFolio))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lbl_libro)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(rb_Entregado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_Pendiente)
                        .addGap(90, 90, 90)
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombrelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombrelibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombrelibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_BuscarFolio;
    public javax.swing.JButton btn_BuscarNombreLibro;
    public javax.swing.JButton btn_Guardar;
    public javax.swing.JComboBox<String> cbx_Libro;
    public javax.swing.ButtonGroup group_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_libro;
    public javax.swing.JRadioButton rb_Entregado;
    public javax.swing.JRadioButton rb_Pendiente;
    public javax.swing.JTable tbl_Devoluciones_Editar;
    public javax.swing.JTextField txt_IdPrestamo;
    public javax.swing.JTextField txt_Nombrelibro;
    // End of variables declaration//GEN-END:variables

}
