/*
 * Rendon Estrada Jorge
 * 04/07/2023
 * Descripcion: Panel de Usuarios_Nuevo que se muestra en el Dashboard 
 * Contiene la tabla de los prestamos y los botones con las acciones
 */

package vistas;

import java.awt.Color;

/**
 *
 * @author Jorge
 */
public class Usuarios_Nuevo extends javax.swing.JPanel {

    /** Creates new form Usuarios */
    public Usuarios_Nuevo() {
        initComponents();
        //Mando a llamar el metodo del LOOK & FEEL
        IniStyles();
        
    }
    
    //Metodo que contiene los estilos del LOOK & FEEL
     private void IniStyles(){
        lbl_Nom.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Nom.setForeground(Color.black);
        lbl_Tel.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Tel.setForeground(Color.black);
        lbl_Direc.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Direc.setForeground(Color.black);
        //Hacer los text area redondeados
        txt_Nombre.putClientProperty( "JComponent.roundRect", true );
        txt_Direct.putClientProperty( "JComponent.roundRect", true );
        txt_Tel.putClientProperty( "JComponent.roundRect", true );
        //Hacer el boton con bordes redondeados
        btn_Guardar.putClientProperty( "JButton.buttonType", "roundRect" );
        
     }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Guardar = new javax.swing.JButton();
        lbl_Nom = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        lbl_Direc = new javax.swing.JLabel();
        txt_Direct = new javax.swing.JTextField();
        lbl_Tel = new javax.swing.JLabel();
        txt_Tel = new javax.swing.JTextField();
        img = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        btn_Guardar.setBackground(new java.awt.Color(0, 1, 248));
        btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btn_Guardar.setText("GUARDAR");

        lbl_Nom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Nom.setText("Ingrese el nombre del usuario:");

        txt_Nombre.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Direc.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Direc.setText("Ingrese la dirección del usuario:");

        txt_Direct.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Tel.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Tel.setText("Ingrese el telefono del usuario:");

        txt_Tel.setForeground(new java.awt.Color(0, 0, 0));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-user.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153))
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Tel)
                                    .addComponent(txt_Direct)
                                    .addComponent(txt_Nombre)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lbl_Direc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lbl_Tel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                        .addGap(86, 86, 86))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbl_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)))
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lbl_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_Direc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Direct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lbl_Tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_Guardar)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton btn_Guardar;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Direc;
    private javax.swing.JLabel lbl_Nom;
    private javax.swing.JLabel lbl_Tel;
    public javax.swing.JTextField txt_Direct;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextField txt_Tel;
    // End of variables declaration//GEN-END:variables

}
