/*
 * Rendon Estrada Jorge
 * 04/07/2023
 * Descripcion: Panel de Usuarios_Nuevo que se muestra en el Dashboard 
 * Contiene la tabla de los prestamos y los botones con las acciones
 */

package vistas;

import java.awt.Color;

/**
 *
 * @author Jorge
 */
public class Usuarios_Editar extends javax.swing.JPanel {

    /** Creates new form Usuarios */
    public Usuarios_Editar() {
        initComponents();
        //Mando a llamar el metodo del LOOK & FEEL
        this.IniStyles();
        //colocar place holder
        TextPrompt bnom = new TextPrompt("Ingrese el nombre", txt_Bname);
        TextPrompt bid = new TextPrompt("Ingrese el ID", txt_Bid);
        
    }
    
    //Metodo que contiene los estilos del LOOK & FEEL
     private void IniStyles(){
        lbl_Nom.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Nom.setForeground(Color.black);
        lbl_Tel.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Tel.setForeground(Color.black);
        lbl_Direc.putClientProperty("FlatLaf.styleClass", "large");
        lbl_Direc.setForeground(Color.black);
        //Hacer los text area redondeados
        txt_Nombre.putClientProperty( "JComponent.roundRect", true );
        txt_Direct.putClientProperty( "JComponent.roundRect", true );
        txt_Tel.putClientProperty( "JComponent.roundRect", true );
        txt_Bname.putClientProperty( "JComponent.roundRect", true );
        txt_Bid.putClientProperty( "JComponent.roundRect", true );
        //Hacer el boton con bordes redondeados
        btn_Guardar.putClientProperty( "JButton.buttonType", "roundRect" );
        btn_Bname.putClientProperty( "JButton.buttonType", "roundRect" );
        btn_Bid.putClientProperty( "JButton.buttonType", "roundRect" );
        //Hacer el comboBox redondeado
        cb_estado.putClientProperty( "JComponent.roundRect", true );
     }
     


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_Bname = new javax.swing.JTextField();
        btn_Bname = new javax.swing.JButton();
        txt_Bid = new javax.swing.JTextField();
        btn_Bid = new javax.swing.JButton();
        lbl_Nom = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        lbl_Direc = new javax.swing.JLabel();
        txt_Direct = new javax.swing.JTextField();
        lbl_Tel = new javax.swing.JLabel();
        txt_Tel = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        txt_Bname.setForeground(new java.awt.Color(0, 0, 0));

        btn_Bname.setBackground(new java.awt.Color(0, 1, 248));
        btn_Bname.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        btn_Bname.setText("Buscar");

        txt_Bid.setForeground(new java.awt.Color(0, 0, 0));

        btn_Bid.setBackground(new java.awt.Color(0, 1, 248));
        btn_Bid.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscar.png"))); // NOI18N
        btn_Bid.setText("Buscar");

        lbl_Nom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Nom.setText("Nombre del usuario:");

        txt_Nombre.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Direc.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Direc.setText("Dirección del usuario:");

        txt_Direct.setForeground(new java.awt.Color(0, 0, 0));

        lbl_Tel.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Tel.setText("Telefono del usuario:");

        txt_Tel.setForeground(new java.awt.Color(0, 0, 0));

        btn_Guardar.setBackground(new java.awt.Color(0, 1, 248));
        btn_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btn_Guardar.setText("GUARDAR");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_user.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Estado");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(txt_Bid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_estado, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lbl_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txt_Nombre)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbl_Tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txt_Tel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txt_Direct)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lbl_Direc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88)))
                        .addGap(26, 26, 26)))
                .addGap(81, 81, 81))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Bid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Bname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Guardar))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbl_Nom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lbl_Direc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Direct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lbl_Tel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    public javax.swing.JButton btn_Bid;
    public javax.swing.JButton btn_Bname;
    public javax.swing.JButton btn_Guardar;
    public javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Direc;
    private javax.swing.JLabel lbl_Nom;
    private javax.swing.JLabel lbl_Tel;
    public javax.swing.JTextField txt_Bid;
    public javax.swing.JTextField txt_Bname;
    public javax.swing.JTextField txt_Direct;
    public javax.swing.JTextField txt_Nombre;
    public javax.swing.JTextField txt_Tel;
    // End of variables declaration//GEN-END:variables

}
