/*
 * Rendon Estrada Jorge 09/05/2023
 * Frame en el cual es la base para todo el proyecto de biblioteca
 */
package pantallas;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
//IMPORTAR  LOS PANELES A MOSTRAR
import vistas.Home;


/**
 *
 * @author FLAKABOY
 */
public class Dashjboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public Dashjboard() {

        initComponents();

        //Mando a llamar el metodo del LOOK & FEEL
        this.IniStyles();

        //Metodo que coloca la fecha en el label
        setDate();

        //Metodo para poner el jpanel correspondiente.
        InitContent();
         Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(Color.blue);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(miColor);
    }

    //Metodos del objeto
    //Metodo que contiene los estilos del LOOK & FEEL
    private void IniStyles() {
        mensaje.putClientProperty("FlatLaf.style", "font: 15 $light.font");
        mensaje.setForeground(Color.black);
        MensajeBiblio.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        MensajeBiblio.setForeground(Color.white);
        fecha.putClientProperty("FlatLaf.style", "font: 25 $light.font");
        fecha.setForeground(Color.white);
        title.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        title.setForeground(Color.white);
    }

    //Metodo para colocar la fecha en el label
    private void setDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    private void InitContent() {
        vista(new Home());
    }

    //Metodo para poner el panel correspondiente
    private void vista(JPanel p) {
        //780,472
        /*
        Se tiene el problema que no se logra adaptar el JPanel importado al
        JPanel de la vista principal lo cual deja al programa con mala estetica
        al no poder lograr hacerlo responsivo. (Maestra ayudeme)
         */
        p.setSize(790, 460);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        menusBtn = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lbl_linea = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_users = new javax.swing.JButton();
        btn_prestamos = new javax.swing.JButton();
        btn_reportes = new javax.swing.JButton();
        btn_devoluciones = new javax.swing.JButton();
        btn_libros = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        MensajeBiblio = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECH Beta 1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1052, 696));

        mensaje.setText("Gracias por evaluar el proyecto 🖤 ");

        menusBtn.setBackground(new java.awt.Color(34, 80, 108));
        menusBtn.setPreferredSize(new java.awt.Dimension(270, 640));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("BIBLIOTECH...");

        lbl_linea.setForeground(new java.awt.Color(255, 255, 255));
        lbl_linea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_linea.setText("____________________________________");

        btn_home.setBackground(new java.awt.Color(0, 74, 143));
        btn_home.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_home.setForeground(new java.awt.Color(255, 255, 255));
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btn_home.setText("HOME");
        btn_home.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_home.setBorderPainted(false);
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_home.setIconTextGap(12);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_users.setBackground(new java.awt.Color(0, 74, 143));
        btn_users.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_users.setForeground(new java.awt.Color(255, 255, 255));
        btn_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users.png"))); // NOI18N
        btn_users.setText("USUARIOS");
        btn_users.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_users.setBorderPainted(false);
        btn_users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_users.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_users.setIconTextGap(12);
        btn_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usersActionPerformed(evt);
            }
        });

        btn_prestamos.setBackground(new java.awt.Color(0, 74, 143));
        btn_prestamos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_prestamos.setForeground(new java.awt.Color(255, 255, 255));
        btn_prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prestamo.png"))); // NOI18N
        btn_prestamos.setText("PRESTAMOS");
        btn_prestamos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_prestamos.setBorderPainted(false);
        btn_prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_prestamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_prestamos.setIconTextGap(12);
        btn_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestamosActionPerformed(evt);
            }
        });

        btn_reportes.setBackground(new java.awt.Color(0, 74, 143));
        btn_reportes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_reportes.setForeground(new java.awt.Color(255, 255, 255));
        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporte.png"))); // NOI18N
        btn_reportes.setText("REPORTES");
        btn_reportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_reportes.setBorderPainted(false);
        btn_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_reportes.setIconTextGap(12);
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });

        btn_devoluciones.setBackground(new java.awt.Color(0, 74, 143));
        btn_devoluciones.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_devoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btn_devoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendario.png"))); // NOI18N
        btn_devoluciones.setText("DEVOLUCIONES");
        btn_devoluciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_devoluciones.setBorderPainted(false);
        btn_devoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_devoluciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_devoluciones.setIconTextGap(12);
        btn_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolucionesActionPerformed(evt);
            }
        });

        btn_libros.setBackground(new java.awt.Color(0, 74, 143));
        btn_libros.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_libros.setForeground(new java.awt.Color(255, 255, 255));
        btn_libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro.png"))); // NOI18N
        btn_libros.setText("LIBROS");
        btn_libros.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_libros.setBorderPainted(false);
        btn_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_libros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_libros.setIconTextGap(12);
        btn_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_librosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menusBtnLayout = new javax.swing.GroupLayout(menusBtn);
        menusBtn.setLayout(menusBtnLayout);
        menusBtnLayout.setHorizontalGroup(
            menusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusBtnLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(menusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_linea, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(menusBtnLayout.createSequentialGroup()
                .addGroup(menusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_libros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_devoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_prestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        menusBtnLayout.setVerticalGroup(
            menusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusBtnLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(title)
                .addGap(6, 6, 6)
                .addComponent(lbl_linea)
                .addGap(73, 73, 73)
                .addGroup(menusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menusBtnLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btn_users, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btn_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_devoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.setBackground(new java.awt.Color(34, 80, 108));
        header.setPreferredSize(new java.awt.Dimension(744, 150));

        MensajeBiblio.setText("Control y Administración de Biblioteca");

        fecha.setText("El día de hoy es {dayname} {day} de {month} del {year}");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(MensajeBiblio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)))
                .addGap(344, 344, 344))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(MensajeBiblio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(fecha)
                .addGap(33, 33, 33))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(mensaje))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(menusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mensaje)
                .addGap(26, 26, 26)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(Color.blue);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(miColor);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolucionesActionPerformed
        // TODO add your handling code here:
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(miColor);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(Color.BLUE);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(miColor);
    }//GEN-LAST:event_btn_devolucionesActionPerformed

    private void btn_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_librosActionPerformed
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(miColor);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(Color.blue);
        btn_reportes.setBackground(miColor);
    }//GEN-LAST:event_btn_librosActionPerformed

    private void btn_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usersActionPerformed
        // TODO add your handling code here:
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(miColor);
        btn_users.setBackground(Color.blue);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(miColor);
    }//GEN-LAST:event_btn_usersActionPerformed

    private void btn_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestamosActionPerformed
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(miColor);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(Color.blue);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(miColor);
    }//GEN-LAST:event_btn_prestamosActionPerformed

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        Color miColor = new Color(0, 74, 143);
        btn_home.setBackground(miColor);
        btn_users.setBackground(miColor);
        btn_prestamos.setBackground(miColor);
        btn_devoluciones.setBackground(miColor);
        btn_libros.setBackground(miColor);
        btn_reportes.setBackground(Color.blue);
    }//GEN-LAST:event_btn_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashjboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MensajeBiblio;
    private javax.swing.JPanel background;
    public javax.swing.JButton btn_devoluciones;
    public javax.swing.JButton btn_home;
    public javax.swing.JButton btn_libros;
    public javax.swing.JButton btn_prestamos;
    public javax.swing.JButton btn_reportes;
    public javax.swing.JButton btn_users;
    public javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lbl_linea;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menusBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
